CREATE TABLE PRODUTO (
    PRODUTO_ID int,
    NOME_PRODUTO varchar(255),
    MARCA_PRODUTO varchar(255),
	QUANTIDADE_PRODUTO int,
	PRECO_PRODUTO int
	);
	
	CREATE TABLE FUNCIONARIO (
    FUNCIONARIO_ID int,
    FIRST_NAME_FUNCIONARIO varchar(255),
    LAST_NAME_FUNCIONARIO varchar(255),
    TELEFONE_FUNCIONARIO varchar(255)
	);
	
	CREATE TABLE CUSTOMER (
    CUSTOMER_ID int,
    FIRST_NAME_CUSTOMER varchar(255),
    LAST_NAME_CUSTOMER varchar(255),
	EMAIL_CUSTOMER varchar(255),
	DOCUMENT_CUSTOMER varchar(255),
    PHONE_CUSTOMER varchar(255),
	ADDRESS_CUSTOMER varchar(255),
	DISTRICT_CUSTOMER varchar(255),
	CITY_CUSTOMER varchar(255)
	);
	
	CREATE TABLE PROVIDER (
    PROVIDER_ID int,
    NAME_PROVIDER varchar(255),
    EMAIL_PROVIDER varchar(255),
	DOCUMENT_PROVIDER varchar(255),
    PHONE_PROVIDER varchar(255),
	ADDRESS_PROVIDER varchar(255),
	DISTRICT_PROVIDER varchar(255),
	CITY_PROVIDER varchar(255)
	);
	
	
	