CREATE TABLE PRODUTO (
    PRODUTO_ID int,
    NOME_PRODUTO varchar(255),
    MARCA_PRODUTO varchar(255),
	QUANTIDADE_PRODUTO int,
	PRECO_PRODUTO int
	);
	
	CREATE TABLE FUNCIONARIO (
    FUNCIONARIO_ID int,
    FIRST_NAME_FUNCIONARIO varchar(255),
    LAST_NAME_FUNCIONARIO varchar(255),
    TELEFONE_FUNCIONARIO varchar(255)
	);
	